### ISSUE TITLE
Update Readme.md File

### ISSUE THREAD

**Issue by CODEx-MMDU** [CODEx-MMDU/Git_-_GitHub#2]
Insert or modify the Readme.md file for looking attractive and Knowledgeable

**Comment by ShivamKr7250** [comment]
Assigne this issue to me

**Comment by ShivamKr7250** [comment]
i have solved the issue

**Comment by CODEx-MMDU** [comment]
thanks for your contribution

**Comment by ShivamKr7250** [comment]
assogn this to me

**Comment by ShivamKr7250** [comment]
Solved the issue
